# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/taktv6/tflow2
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -v

      - run: go get github.com/mattn/goveralls
      - run: go test -v -cover -race -coverprofile=coverage.out ./...
      - run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - run: go install github.com/taktv6/tflow2

  checks:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/taktv6/tflow2
    steps:
      - checkout

      # check goftm
      - run: .circleci/gofmt.sh

      # check misspell
      - run: go get github.com/client9/misspell/cmd/misspell
      - run: misspell -error .

workflows:
  version: 2
  workflow:
    jobs:
    - checks
    - build