// Code generated by protoc-gen-go.
// source: netflow.proto
// DO NOT EDIT!

/*
Package netflow is a generated protocol buffer package.

It is generated from these files:
	netflow.proto

It has these top-level messages:
	Pfx
	Flow
	Intf
	Flows
*/
package netflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Pfx defines an IP prefix
type Pfx struct {
	// IPv4 or IPv6 address
	IP []byte `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	// Netmask
	Mask []byte `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (m *Pfx) Reset()                    { *m = Pfx{} }
func (m *Pfx) String() string            { return proto.CompactTextString(m) }
func (*Pfx) ProtoMessage()               {}
func (*Pfx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pfx) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *Pfx) GetMask() []byte {
	if m != nil {
		return m.Mask
	}
	return nil
}

// Flow defines a network flow
type Flow struct {
	// Router flow was received from
	Router []byte `protobuf:"bytes,1,opt,name=router,proto3" json:"router,omitempty"`
	// Address family
	Family uint32 `protobuf:"varint,2,opt,name=family" json:"family,omitempty"`
	// SRC IP address
	SrcAddr []byte `protobuf:"bytes,3,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	// DST IP address
	DstAddr []byte `protobuf:"bytes,4,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	// Protocol
	Protocol uint32 `protobuf:"varint,5,opt,name=protocol" json:"protocol,omitempty"`
	// Number of packets
	Packets uint32 `protobuf:"varint,6,opt,name=packets" json:"packets,omitempty"`
	// Size of flow
	Size uint64 `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	// SNMP interface id flow was received on
	IntIn uint32 `protobuf:"varint,8,opt,name=int_in,json=intIn" json:"int_in,omitempty"`
	// SNMP interface if flow was transmitted on
	IntOut uint32 `protobuf:"varint,9,opt,name=int_out,json=intOut" json:"int_out,omitempty"`
	// Next Hop IP address
	NextHop []byte `protobuf:"bytes,10,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// SRC ASN
	SrcAs uint32 `protobuf:"varint,11,opt,name=src_as,json=srcAs" json:"src_as,omitempty"`
	// DST ASN
	DstAs uint32 `protobuf:"varint,12,opt,name=dst_as,json=dstAs" json:"dst_as,omitempty"`
	// NEXT HOP ASN
	NextHopAs uint32 `protobuf:"varint,13,opt,name=next_hop_as,json=nextHopAs" json:"next_hop_as,omitempty"`
	// Unix timestamp
	Timestamp int64 `protobuf:"varint,14,opt,name=timestamp" json:"timestamp,omitempty"`
	// SRC prefix
	SrcPfx *Pfx `protobuf:"bytes,15,opt,name=src_pfx,json=srcPfx" json:"src_pfx,omitempty"`
	// DST perfix
	DstPfx *Pfx `protobuf:"bytes,16,opt,name=dst_pfx,json=dstPfx" json:"dst_pfx,omitempty"`
	// SRC port
	SrcPort uint32 `protobuf:"varint,17,opt,name=src_port,json=srcPort" json:"src_port,omitempty"`
	// DST port
	DstPort uint32 `protobuf:"varint,18,opt,name=dst_port,json=dstPort" json:"dst_port,omitempty"`
	// Samplerate
	Samplerate uint64 `protobuf:"varint,19,opt,name=samplerate" json:"samplerate,omitempty"`
}

func (m *Flow) Reset()                    { *m = Flow{} }
func (m *Flow) String() string            { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()               {}
func (*Flow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Flow) GetRouter() []byte {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Flow) GetFamily() uint32 {
	if m != nil {
		return m.Family
	}
	return 0
}

func (m *Flow) GetSrcAddr() []byte {
	if m != nil {
		return m.SrcAddr
	}
	return nil
}

func (m *Flow) GetDstAddr() []byte {
	if m != nil {
		return m.DstAddr
	}
	return nil
}

func (m *Flow) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *Flow) GetPackets() uint32 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *Flow) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Flow) GetIntIn() uint32 {
	if m != nil {
		return m.IntIn
	}
	return 0
}

func (m *Flow) GetIntOut() uint32 {
	if m != nil {
		return m.IntOut
	}
	return 0
}

func (m *Flow) GetNextHop() []byte {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *Flow) GetSrcAs() uint32 {
	if m != nil {
		return m.SrcAs
	}
	return 0
}

func (m *Flow) GetDstAs() uint32 {
	if m != nil {
		return m.DstAs
	}
	return 0
}

func (m *Flow) GetNextHopAs() uint32 {
	if m != nil {
		return m.NextHopAs
	}
	return 0
}

func (m *Flow) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Flow) GetSrcPfx() *Pfx {
	if m != nil {
		return m.SrcPfx
	}
	return nil
}

func (m *Flow) GetDstPfx() *Pfx {
	if m != nil {
		return m.DstPfx
	}
	return nil
}

func (m *Flow) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Flow) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *Flow) GetSamplerate() uint64 {
	if m != nil {
		return m.Samplerate
	}
	return 0
}

// Intf groups an interfaces ID and name
type Intf struct {
	// ID is an interface ID
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// name is an interfaces name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Intf) Reset()                    { *m = Intf{} }
func (m *Intf) String() string            { return proto.CompactTextString(m) }
func (*Intf) ProtoMessage()               {}
func (*Intf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Intf) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Intf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Flows defines a groups of flows
type Flows struct {
	// Group of flows
	Flows []*Flow `protobuf:"bytes,1,rep,name=flows" json:"flows,omitempty"`
	// Mapping of interface names to IDs
	InterfaceMapping []*Intf `protobuf:"bytes,2,rep,name=interface_mapping,json=interfaceMapping" json:"interface_mapping,omitempty"`
}

func (m *Flows) Reset()                    { *m = Flows{} }
func (m *Flows) String() string            { return proto.CompactTextString(m) }
func (*Flows) ProtoMessage()               {}
func (*Flows) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Flows) GetFlows() []*Flow {
	if m != nil {
		return m.Flows
	}
	return nil
}

func (m *Flows) GetInterfaceMapping() []*Intf {
	if m != nil {
		return m.InterfaceMapping
	}
	return nil
}

func init() {
	proto.RegisterType((*Pfx)(nil), "netflow.pfx")
	proto.RegisterType((*Flow)(nil), "netflow.Flow")
	proto.RegisterType((*Intf)(nil), "netflow.Intf")
	proto.RegisterType((*Flows)(nil), "netflow.Flows")
}

func init() { proto.RegisterFile("netflow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0xb4, 0x69, 0xa7, 0xcd, 0xb2, 0x6b, 0x04, 0x18, 0x84, 0x56, 0x51, 0x11, 0x52,
	0xe0, 0xb0, 0x87, 0xe5, 0xc6, 0x6d, 0x2f, 0x88, 0x1e, 0x10, 0x55, 0xfe, 0x40, 0x64, 0x12, 0x87,
	0xb5, 0x36, 0xb1, 0x2d, 0x7b, 0xaa, 0x0d, 0xfc, 0x0b, 0xfe, 0x31, 0x1a, 0x3b, 0x2d, 0x08, 0x71,
	0xf3, 0xbc, 0xf7, 0x66, 0xfc, 0xe6, 0x03, 0x72, 0x2d, 0xb1, 0xeb, 0xcd, 0xe3, 0x8d, 0x75, 0x06,
	0x0d, 0xcb, 0xa6, 0x70, 0xf7, 0x0e, 0xe6, 0xb6, 0x1b, 0xd9, 0x05, 0xcc, 0xf6, 0x07, 0x9e, 0x14,
	0x49, 0xb9, 0xad, 0x66, 0xfb, 0x03, 0x63, 0x90, 0x0e, 0xc2, 0x3f, 0xf0, 0x59, 0x40, 0xc2, 0x7b,
	0xf7, 0x2b, 0x85, 0xf4, 0x53, 0x6f, 0x1e, 0xd9, 0x73, 0x58, 0x3a, 0x73, 0x44, 0xe9, 0xa6, 0x84,
	0x29, 0x22, 0xbc, 0x13, 0x83, 0xea, 0x7f, 0x84, 0xb4, 0xbc, 0x9a, 0x22, 0xf6, 0x12, 0x56, 0xde,
	0x35, 0xb5, 0x68, 0x5b, 0xc7, 0xe7, 0x21, 0x23, 0xf3, 0xae, 0xb9, 0x6b, 0x5b, 0x47, 0x54, 0xeb,
	0x31, 0x52, 0x69, 0xa4, 0x5a, 0x8f, 0x81, 0x7a, 0x05, 0xab, 0xe0, 0xb5, 0x31, 0x3d, 0x5f, 0x84,
	0x7a, 0xe7, 0x98, 0x71, 0xc8, 0xac, 0x68, 0x1e, 0x24, 0x7a, 0xbe, 0x0c, 0xd4, 0x29, 0x24, 0xe3,
	0x5e, 0xfd, 0x94, 0x3c, 0x2b, 0x92, 0x32, 0xad, 0xc2, 0x9b, 0x3d, 0x83, 0xa5, 0xd2, 0x58, 0x2b,
	0xcd, 0x57, 0x41, 0xbc, 0x50, 0x1a, 0xf7, 0x9a, 0xbd, 0x80, 0x8c, 0x60, 0x73, 0x44, 0xbe, 0x8e,
	0x7e, 0x95, 0xc6, 0xaf, 0x47, 0x24, 0x53, 0x5a, 0x8e, 0x58, 0xdf, 0x1b, 0xcb, 0x21, 0x9a, 0xa2,
	0xf8, 0xb3, 0xb1, 0x54, 0x2a, 0xb4, 0xe2, 0xf9, 0x26, 0x96, 0xa2, 0x46, 0x3c, 0xc1, 0xa1, 0x0d,
	0xcf, 0xb7, 0x11, 0xa6, 0x26, 0x3c, 0xbb, 0x86, 0xcd, 0xa9, 0x10, 0x71, 0x79, 0xe0, 0xd6, 0x53,
	0xad, 0x3b, 0xcf, 0x5e, 0xc3, 0x1a, 0xd5, 0x20, 0x3d, 0x8a, 0xc1, 0xf2, 0x8b, 0x22, 0x29, 0xe7,
	0xd5, 0x1f, 0x80, 0xbd, 0x05, 0x1a, 0x53, 0x6d, 0xbb, 0x91, 0x3f, 0x29, 0x92, 0x72, 0x73, 0xbb,
	0xbd, 0x39, 0x2f, 0xb1, 0x1b, 0x2b, 0x32, 0x72, 0xe8, 0x46, 0x92, 0xd1, 0xdf, 0x24, 0xbb, 0xfc,
	0x9f, 0xac, 0xf5, 0x48, 0xb2, 0x69, 0x09, 0xd6, 0x38, 0xe4, 0x57, 0x71, 0x66, 0x54, 0xc0, 0x38,
	0x3c, 0x2d, 0x21, 0x50, 0x2c, 0x52, 0x94, 0x44, 0xd4, 0x35, 0x80, 0x17, 0x83, 0xed, 0xa5, 0x13,
	0x28, 0xf9, 0xd3, 0x30, 0xd4, 0xbf, 0x90, 0xdd, 0x7b, 0x48, 0xf7, 0x1a, 0x3b, 0xba, 0x1f, 0xd5,
	0x86, 0x73, 0xc8, 0xab, 0x99, 0x6a, 0x69, 0x0d, 0x5a, 0x0c, 0x32, 0x1c, 0xc2, 0xba, 0x0a, 0xef,
	0xdd, 0x3d, 0x2c, 0xe8, 0x7c, 0x3c, 0x7b, 0x03, 0x0b, 0xb2, 0xe7, 0x79, 0x52, 0xcc, 0xcb, 0xcd,
	0x6d, 0x7e, 0xf6, 0x4b, 0x74, 0x15, 0x39, 0xf6, 0x11, 0xae, 0x94, 0x46, 0xe9, 0x3a, 0xd1, 0xc8,
	0x7a, 0x10, 0xd6, 0x2a, 0xfd, 0x9d, 0xcf, 0xfe, 0x49, 0xa0, 0xbf, 0xab, 0xcb, 0xb3, 0xee, 0x4b,
	0x94, 0x7d, 0x5b, 0x86, 0x43, 0xf9, 0xf0, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x75, 0x0d, 0xbe, 0x40,
	0xf5, 0x02, 0x00, 0x00,
}
